---

- name: "{{ service.name }}: Copy compose"
  ansible.builtin.template:
    src: "container_service_files/{{ service.name }}/docker-compose.yml.j2"
    dest: "{{ container_service_basedir }}/{{ service.name }}/docker-compose.yml"
    mode: "{{ item.mode | default( default_file_mode ) }}"
    owner: "{{ item.owner | default( operator_user ) }}"
    group: "{{ item.volume.owner | default( operator_group ) }}"
  #    validate: "docker-compose -f %s config" # TODO, currently throws an error
  register: "changed_container"
  notify: [ "Stop Service", "Start Service" ]

- name: "Flush handlers"
  ansible.builtin.meta: "flush_handlers"
